name: khotwa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dotted_border: ^2.0.0
  flutter_bloc: ^8.1.6 
  flutter_svg: ^2.0.16 
  smooth_page_indicator: ^1.2.0+3 
  percent_indicator: ^4.2.4 
  fl_chart: ^0.69.2
  keyboard_dismisser: ^3.0.0
  get: ^4.6.6
  sqflite: ^2.4.1
  flutter_launcher_icons: ^0.14.2
  file_picker: ^5.2.2
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.5
  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  
  fonts:
    - family: Khmer MN
      fonts:
        - asset: assets/fonts/khmer-mn.ttf
        
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
    

    - family: DM Sans Italic
      fonts:
        - asset: assets/fonts/DMSans-Italic.ttf

flutter_icons:
  ios: true
  image_path: "assets/icon.png"